### ISSUE TITLE
[Feature] Timer for the Night

### ISSUE THREAD

**Issue by freswa** [mudar/Fairphone#21]
I know many of those "Task" Apps, which can do a lot depending on the clock. But they have so many confusing features. I only want to get disconnected from the digital world why I am resting or sleeping, so this apps seems to be suitable for me :).

What I would really like:
Add a scheduler for each day of the week for which one can use the disconnect feature automatically.

**Comment by fschwan** [comment]
Sorry, duplicate of #17
